POST http://localhost:3001/api/post
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTljMzA4OTYwYzlhOTdiNjUyNGNlNiIsImlhdCI6MTY1MDA1MDA5MywiZXhwIjoxNjgxNjA3MDQ1fQ.nw3QoSTS8Agm_sk4pAKM2TyiivmmZy9JfmTRbPL0fIk

{
  "content": "Test Post",
  "userId": "6259c308960c9a97b6524ce6"
}
### Test error
POST http://localhost:3001/api/post
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTljMzA4OTYwYzlhOTdiNjUyNGNlNiIsImlhdCI6MTY1MDA1MDA5MywiZXhwIjoxNjgxNjA3MDQ1fQ.nw3QoSTS8Agm_sk4pAKM2TyiivmmZy9JfmTRbPL0fIk

{
  "content": "Data rule the world"
}
### Test error
POST http://localhost:3001/api/post
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTljMzA4OTYwYzlhOTdiNjUyNGNlNiIsImlhdCI6MTY1MDA1MDA5MywiZXhwIjoxNjgxNjA3MDQ1fQ.nw3QoSTS8Agm_sk4pAKM2TyiivmmZy9JfmTRbPL0fIk

{
  "userId": "6259c308960c9a97b6524ce6"
}
### Test error
POST http://localhost:3001/api/post
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTljMzA4OTYwYzlhOTdiNjUyNGNlNiIsImlhdCI6MTY1MDA1MDA5MywiZXhwIjoxNjgxNjA3MDQ1fQ.nw3QoSTS8Agm_sk4pAKM2TyiivmmZy9JfmTRbPL0fIk
###
POST http://localhost:3001/api/post
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTljMzA4OTYwYzlhOTdiNjUyNGNlNiIsImlhdCI6MTY1MDA1MDA5MywiZXhwIjoxNjgxNjA3MDQ1fQ.nw3QoSTS8Agm_sk4pAKM2TyiivmmZy9JfmTRbPL0fIk

{
  "content": "Test Post",
  "likes": [{
      "userId": "6259c308960c9a97b6524ce6"
  }],
  "comments": [{
      "content": "Test Comment",
      "userId": "6259c308960c9a97b6524ce6"
  }],
  "userId": "6259c308960c9a97b6524ce6"
}